# Stage 1: ビルド環境
FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Nginxで起動
RUN npm run build

# Stage 2: 実行環境 (Nginx)
FROM nginx:stable-alpine
# ビルダーからビルド済みの静的ファイルをコピー
COPY --from=builder /app/dist /usr/share/nginx/html
# Nginxの設定ファイルをコピー
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]