# 開発用はNode.jsイメージを直接使う
FROM node:22-alpine

# 作業ディレクトリを設定
WORKDIR /app

# 依存関係のファイルを先にコピーしてキャッシュを有効活用
COPY package*.json ./

# 依存関係をインストール
#（Composeのcommandでも実行するが、イメージビルド時にも行なっておくと安定する）
RUN npm install

# アプリケーションのポートを公開
EXPOSE 5173

# デフォルトのコマンドとして開発サーバーを起動
CMD ["npm", "run", "dev"]